---
- name: Update API key in 1Password
  ansible.builtin.shell:
    cmd: echo 'op item edit "Komodo" --vault "Docker" "komodo_api_key={{ komodo_auth_api_key }}"' > /tmp/update-op.sh
  no_log: false
  changed_when: true

- name: Update API secret in 1Password
  ansible.builtin.shell:
    cmd: echo 'op item edit "Komodo" --vault "Docker" "komodo_api_secret={{ komodo_auth_api_secret }}"' >> /tmp/update-op.sh
  no_log: false
  changed_when: true

# - name: Run 1Password update script
#   ansible.builtin.shell:
#     cmd: bash /tmp/update-op.sh
#   no_log: false
#   changed_when: true

- name: Wait for user to run bash script to update 1Password
  ansible.builtin.pause:
    prompt: "Please run: bash /tmp/update-op.sh && rm /tmp/update-op.sh once completed. Press Enter to continue or Ctrl+C to abort."

- name: Verify API keys were stored
  ansible.builtin.command: op item get "Komodo" --vault "Docker" --fields komodo_api_key
  register: komodo_auth_verify_api_key
  changed_when: false
  no_log: false
