---
version: "3"

vars:
  ANSIBLE_OPTS: "-i inventory/"
  ANSIBLE_VERBOSE: ""

set: [pipefail]
tasks:
  default: task --list

  check-hosts:
    desc: Check connectivity to all hosts in the Ansible inventory
    cmd: ansible all ${ANSIBLE_VERBOSE} -i inventory/ -m ping

  deploy:
    desc: Deploy complete Komodo infrastructure
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ site.yml

  install-01-docker:
    desc: 🐳 Install Docker on all nodes
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ playbooks/01_docker.yml

  install-02-core:
    desc: 🦎 Deploy Komodo Core
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ playbooks/02_komodo_core.yml

  install-03-auth:
    desc: 🔑 Initialize Komodo Authentication
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ playbooks/03_komodo_auth.yml

  install-04-periphery:
    desc: 🔗 Deploy Komodo Periphery
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ playbooks/04_komodo_periphery.yml

  install-05-nfs:
    desc: 🔗 Deploy Komodo Periphery
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ playbooks/05_nfs.yml

  install-06-komodo-op-vars:
    desc: 🔐 Bootstrap komodo-op variables...
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ playbooks/06_bootstrap_komodo_op.yml

  install-07-komodo-op:
    desc: 🔐 Deploy komodo-op stack...
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ playbooks/07_deploy_komodo_op.yml

  install-08-komodo-op:
    desc: 🔐 Deploy app-syncs...
    cmd: ansible-playbook ${ANSIBLE_VERBOSE} -i inventory/ playbooks/08_app_syncs.yml

  inventory:
    desc: View Ansible Inventory as built by Terraform
    cmd: ansible-inventory ${ANSIBLE_VERBOSE} -i inventory/ --graph --vars

  setup:
    desc: Setup Ansible and install ansible modules/collections
    cmds:
      - |
        pip install ansible &&
        ansible-galaxy collection install -r ansible/requirements.yml &&
        ansible-galaxy install -r ansible/requirements.yml -p ~/.ansible/roles
